# Generated by Django 4.0.5 on 2022-06-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_produit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
