# Generated by Django 4.0.5 on 2022-06-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_produit_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='commande',
            fields=[
                ('id_c', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('prix', models.IntegerField(default=0)),
                ('quantite', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fournisseur',
            fields=[
                ('id_f', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
