# Generated by Django 4.0.5 on 2022-06-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commande_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
