# Generated by Django 4.0.5 on 2022-06-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_produit_image_alter_produit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.FileField(default='', upload_to='static/'),
        ),
    ]
